apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wip-planner-db
  labels:
    app: wip-planner-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
